name: gha_example: GitHub Action exercise

on:
  workflow_dispatch:
    # push:
    #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Buildx set-up
        uses: docker/setup-buildx-action@v1

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64/v8,linux/amd64
          context: .
          file: Dockerfile
          push: true
          tags: |
            alinakatrych1/lab10:arm64v8-latest
            alinakatrych1/lab10:amd64-latest

